"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import glob

APP = ["cuteplayer.py"]
DATA_FILES = [("utils", glob.glob("utils"))]
OPTIONS = {
    "packages": ["mutagen", "tk", "youtube-dl", "python-mpv", "tkmacosx"],
    "iconfile": "pics/cato.icns",
    "plist": {
        "CFBundleDevelopmentRegion": "English",
        "CFBundleIdentifier": "com.cuteplayer.xxx",
    },
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
