"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import glob

APP = ["cuteplayer.py"]
DATA_FILES = ["utils", "libmpv.dylib"]
OPTIONS = {
    "packages": [
        "mutagen",
        "tk",
        "youtube_dl",
        "mpv",
        "tkmacosx",
        "pygame",
    ],
    "iconfile": "pics/cato.icns",
    "plist": {
        "CFBundleDevelopmentRegion": "English",
        "CFBundleIdentifier": "com.cuteplayer.xxx",
    },
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
