name: Builds

on:
  push:
    branches:
      - MacOs

  pull_request:
    branches:
      - MacOs

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  MacBuild:
    name: Build for MacOs
    runs-on: macos-latest
    if: github.ref == 'refs/heads/MacOs'
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: master

      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
          architecture: "x64"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Build App
        run: |
          python3 setup.py bdist_dmg

      - name: Push to releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/cuteplayer-1.0.dmg
          asset_name: ${{ matrix.asset_name }}
          # tag: ${{ github.ref }}
          tag: "v1.0"
          overwrite: true
          body: "Latest"

      - name: Archive build files
        uses: actions/upload-artifact@v2
        with:
          name: MacOs Installer
          path: build/cuteplayer-1.0.dmg

      - name: Display directory
        run: ls
