name: Builds

on:
  push:
    branches:
      - master
      - WindowsBuild

  pull_request:
    branches:
      - master
      - WindowsBuild

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  LinuxBuild:
    name: Build for Linux
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/dummy'
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: master

      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
          architecture: "x64"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Build App
        run: |
          python3 setup.py build

        # Upload build files
      - name: Archive build files
        uses: actions/upload-artifact@v2
        with:
          name: Linux build Files
          path: build

      - name: Display directory
        run: tree

  MacBuild:
    name: Build for MacOs
    runs-on: macos-latest
    # if: github.ref == 'refs/heads/MacOs' # Run on push from MacOs branch
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: master

      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
          architecture: "x64"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Build App
        run: |
          python3 setup.py bdist_dmg

        # Upload build files
      - name: Archive build files
        uses: actions/upload-artifact@v2
        with:
          name: MacOs build Files
          path: build/cuteplayer-1.0.dmg

      - name: Display directory
        run: ls

  WindowsBuild:
    name: Build for Windows
    runs-on: windows-latest
    # if: github.ref == 'refs/heads/WindowsBuild'
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          lfs: true
          ref: WindowsBuild
      - name: Checkout LFS files
        run: git lfs checkout
        
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
          architecture: "x64"

      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Create Windows Installer
        run: python3 setup.py bdist_msi
        shell: bash

      - name: Push to releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cuteplayer-installer/cuteplayer-1.0-amd64.msi
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
          body: "Latest"

        # Upload build files
      - name: Archive build files
        uses: actions/upload-artifact@v2
        with:
          name: Windows Installer
          path: cuteplayer-installer/cuteplayer-1.0-amd64.msi

      - name: Display directory
        run: tree
