name: CI

on:
  push:
    branches: [master, WindowsBuild]
  pull_request:
    branches: [master, WindowsBuild]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  LinuxBuild:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: master

      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
          architecture: "x64"

      - name: Install dependencies
        run: |

      - name: Build App
        run: |
          python -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          python3 setup.py build

        # Upload build files
      - name: Archive build files
        uses: actions/upload-artifact@v2
        with:
          name: Linux build Files
          path: build

      - name: Display directory
        run: tree

  MacBuild:
    name: Build for MacOs
    runs-on: macos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: master

      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
          architecture: "x64"

      - name: Install dependencies
        run: |

      - name: Build App
        run: |
          python -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          python3 setup.py build

        # Upload build files
      - name: Archive build files
        uses: actions/upload-artifact@v2
        with:
          name: MacOs build Files
          path: build

      - name: Display directory
        run: tree

  WindowsBuild:
    name: Build for Windows
    runs-on: windows-latest
    if: github.ref == 'refs/heads/WindowsBuild'
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: WindowsBuild

      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
          architecture: "x64"

      - name: Create Windows Installer
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            python -m pip install --upgrade pip
            python3 -m pip install -r requirements.txt
            python3 setup.py bdist_msi
          fi
        shell: bash

      - name: Push to releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cuteplayer-installer/cuteplayer-1.0-amd64.msi
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
          body: "Latest"

        # Upload build files
      - name: Archive build files
        uses: actions/upload-artifact@v2
        with:
          name: Windows Installer
          path: cuteplayer-installer/cuteplayer-1.0-amd64.msi

      - name: Display directory
        run: tree
